// review-deck.js — the two-reviewer pass Kristian asked for (2026-10-07): a Sonnet CORE-MESSAGE investigator (per slide:
// is the so-what stated? exact fix, source line, skill improvements) and an Opus ART DIRECTOR at extra-high effort
// (flow, core message, emotion, data, logic; P1/P2/P3 fixes). Both read-only; the lead applies the fixes.
// Prereqs the lead stages first: reviews/slide-map.md (index|type|title), reviews/source-*.md (the source text),
// the rendered out/<render>/sheet-*.png + slide-NN.png, deck.json.
// args: { deck: "maps-ft.json", render: "out/maps-render", source: "reviews/source-maps.md", client: "TMC",
//         audience: "<who sees it, who presents>", outDir: "reviews" }
export const meta = { name: 'ft-deck-review', description: 'Sonnet core-message investigator + Opus art director (xhigh) on a built deck', phases: [{ title: 'Review' }] }
const SCHEMA = { type: 'object', required: ['report', 'top_fixes', 'verdict'], properties: { report: { type: 'string', description: 'path of the written report' }, top_fixes: { type: 'array', items: { type: 'string' }, description: 'slide index → one-line change' }, verdict: { type: 'string' } } }
const TL = '!! COMMAND TIME LIMIT: every shell command < 150 s. Read-only except your report file. !!\n'
const common = `${TL}Deck source: ${args.deck}. Renders: ${args.render}/sheet-*.png (READ all) and ${args.render}/slide-NN.png (0-based). Index: ${args.outDir}/slide-map.md. Original source text: ${args.source}. Client: ${args.client}. Audience: ${args.audience}. House system: ~/.claude/skills/ft-deck/references/design-system.md (read §11 "Every slide carries a message") and archetypes.md.\n`
const core = agent(common + `You are the CORE-MESSAGE INVESTIGATOR. Core message = the one sentence a viewer repeats: claim + direction + number + consequence for ${args.client}. A label or topic is not one. Missing = data shown, meaning never stated. Buried = only in notes or a 16-pt sub.
Write ${args.outDir}/core-message-sonnet.md: (A) table per slide: index | title | present/weak/missing | the core message as it should read (≤ 18 words, one *yellow* span) | where it lives (title/sub/row/footer/sowhat) | source line; (B) top 10 fixes as exact JSON field changes; (C) flow gaps: chapters without an opening claim (chapter sub) or a closing "What this means for ${args.client}" slide, with the slide to add; (D) new rules/checker ideas for the skill if any pattern is not yet covered by check_titles.py. Cite the source for every number; never propose cutting content.`, { model: 'sonnet', schema: SCHEMA, label: 'review:core-message', phase: 'Review' })
const art = agent(common + `You are the ART DIRECTOR (most demanding senior creative + strategy director) judging the deck before it goes to ${args.client} across FLOW, CORE MESSAGE, EMOTION, DATA, LOGIC. Every row/idea appears on a click; graphic slides morph from a start state.
Write ${args.outDir}/art-director-opus.md: (1) verdict in 5 lines + the one change that moves it most; (2) FLOW: the chapter arc, drags, jumps, merge/move/add, does the opening land, does the ending ask for a decision; (3) CORE MESSAGE per chapter: the sentence the client must repeat, which slides state it, title rewrites (≤ 18 words); (4) EMOTION: where the client feels the problem, where it stays clinical, what to intensify within the system (hero number, before/after, versus, photo, pause slide), no decoration; (5) DATA: every number checked against the source — mismatches, unit inconsistencies, missing (F)/(I)/(H) marks, highlights that contradict titles; (6) LOGIC: claims without evidence on the slide or in notes, non-sequiturs, what a sceptical CFO attacks first; (7) FIX LIST P1/P2/P3 as slide index → problem → exact change (JSON field + text, or add slide, or move), plus 3 things that must not be touched; (8) 5 rules for the skill. Fast Track register; every number traced; never propose cutting content.`, { model: 'opus', effort: 'xhigh', schema: SCHEMA, label: 'review:art-director', phase: 'Review' })
const [coreR, artR] = await Promise.all([core, art])
return { core: coreR, art: artR }
