// verify-and-fix.js — after the lead rendered the merged deck: one checker per chapter reads the slide PNGs and the
// check_deck.py output, then (optionally) one fixer per failing chapter edits only its deck.json slice.
// args: { render: "<dir with slide-NN.png + sheets>", lint: "<check_deck.py output>", chapters: [{ id, title, file, slides: "NN-MM" }], fix?: bool, checkModel?, fixModel? }
export const meta = { name: 'ft-deck-verify-fix', description: 'Per-chapter visual checkers on the rendered deck, then fixers on failing slices', phases: [{ title: 'Verify' }, { title: 'Fix' }] }
const CHECK = { type: 'object', required: ['pass', 'evidence', 'failures'], properties: { pass: { type: 'boolean' }, evidence: { type: 'string' }, failures: { type: 'array', items: { type: 'string' } } } }
const FIX = { type: 'object', required: ['summary', 'fixed', 'not_fixed'], properties: { summary: { type: 'string' }, fixed: { type: 'array', items: { type: 'string' } }, not_fixed: { type: 'array', items: { type: 'string' } } } }
const TL = '!! COMMAND TIME LIMIT: every shell command < 150 s. !!\n'
const checks = await parallel(args.chapters.map((c) => () => agent(`${TL}You are the CHECKER for chapter ${c.id} "${c.title}" (slides ${c.slides}). Never fix; only verify. Read ~/.claude/skills/ft-deck/references/design-system.md §Density and §Archetype rules, then READ every slide PNG of your chapter in ${args.render} (slide-NN.png, 0-based). Lint output: ${args.lint}\nProve each: (1) one idea + one highlighted number per slide; (2) no clipped/overlapping text, nothing off-canvas, labels readable; (3) yellow only on the thing the slide is about, grey for context; (4) numbers match the source data in ${c.file}; (5) ≤ 20 words unless it is a table; (6) photos dark and faded under text. pass=true only with evidence per criterion; failures as "slide NN: what, expected".`, { model: args.checkModel || 'sonnet', schema: CHECK, label: 'verify:' + c.id, phase: 'Verify' })))
if (!args.fix) return checks
const fixes = await parallel(args.chapters.map((c, i) => () => checks[i] && !checks[i].pass ? agent(`${TL}You are the FIXER for chapter ${c.id}. Edit ONLY ${c.file} (a deck.json slice; archetype options in ~/.claude/skills/ft-deck/references/archetypes.md). Failures to fix: ${JSON.stringify(checks[i].failures)}. Do not rebuild the pptx; the lead does. Report what you changed per failure.`, { model: args.fixModel, schema: FIX, label: 'fix:' + c.id, phase: 'Fix' }) : Promise.resolve(null)))
return args.chapters.map((c, i) => ({ id: c.id, check: checks[i], fix: fixes[i] }))
